language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-meteor-stock' ]; then cd .. && eval "mv $currentfolder generator-meteor-stock" && cd generator-meteor-stock; fi

